# Create a GitHub action to email a report from a file at 6 a.m. daily.
# The report is created by the deploy-app.yaml file

name: Email Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email_report:
    runs-on: ubuntu-latest
    steps:
    - name: Email the report
      run: |
        echo "Hello, this is the report" > report.txt
        mail -s "Daily report"